// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVnqhyZ_NrvcJXNchqhNxKErvarvlraKw',
    appId: '1:319980438632:web:6abeb696134597ac89a7dd',
    messagingSenderId: '319980438632',
    projectId: 'blood-bank-management-5dbac',
    authDomain: 'blood-bank-management-5dbac.firebaseapp.com',
    storageBucket: 'blood-bank-management-5dbac.firebasestorage.app',
    measurementId: 'G-RT671XS765',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh_S27TUOQ61QdeX16UrmUhIl_DkLVTCo',
    appId: '1:319980438632:android:d787da4ffca5947f89a7dd',
    messagingSenderId: '319980438632',
    projectId: 'blood-bank-management-5dbac',
    storageBucket: 'blood-bank-management-5dbac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbSFMf9VYYdRcBJSBnxS7ytbKrnjStsBk',
    appId: '1:319980438632:ios:10f938f3933cf00189a7dd',
    messagingSenderId: '319980438632',
    projectId: 'blood-bank-management-5dbac',
    storageBucket: 'blood-bank-management-5dbac.firebasestorage.app',
    iosBundleId: 'com.example.bloodBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbSFMf9VYYdRcBJSBnxS7ytbKrnjStsBk',
    appId: '1:319980438632:ios:10f938f3933cf00189a7dd',
    messagingSenderId: '319980438632',
    projectId: 'blood-bank-management-5dbac',
    storageBucket: 'blood-bank-management-5dbac.firebasestorage.app',
    iosBundleId: 'com.example.bloodBank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVnqhyZ_NrvcJXNchqhNxKErvarvlraKw',
    appId: '1:319980438632:web:6453c0d66124c33389a7dd',
    messagingSenderId: '319980438632',
    projectId: 'blood-bank-management-5dbac',
    authDomain: 'blood-bank-management-5dbac.firebaseapp.com',
    storageBucket: 'blood-bank-management-5dbac.firebasestorage.app',
    measurementId: 'G-KCZBFV4CR6',
  );
}
